name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        working-directory: PROVASIM9_LB/MeuCurriculo
        run: dotnet restore

      - name: Build do projeto
        working-directory: PROVASIM9_LB/MeuCurriculo
        run: dotnet build --configuration Release --no-restore